### ISSUE TITLE
Error parsing one subscription

### ISSUE THREAD

**Issue by Zahrun** [Tubefeeder/Pipeline#154]
It was working fine but now stopped working for thelinuxexperiment@tilvids.com
```
2023-07-27T09:07:55Z ERROR tf_utils::rss::rss_extractor] Error parsing: Expecting Start event
```

**Comment by Schmiddiii** [comment]
From <https://tilvids.com/c/thelinuxexperiment_channel/videos>, the channel ID is <thelinuxexperiment_channel@tilvids.com> (note the `_channel`).

Note that this does currently not work due to the following issue, but is already fixed on master:

```
[2023-07-28T09:30:25Z ERROR tf_utils::rss::rss_extractor] Error parsing: duplicate field `media/thumbnail`

```

**Comment by Zahrun** [comment]
Ok, please let me know when there is a new release shipping that fix.
I am using the flatpak version.

**Comment by Schmiddiii** [comment]
The version 1.12.0 should be on Flathub in a few hours. This should fix the problem.

I am going to close this now as this should be fixed after the update.

**Comment by Zahrun** [comment]
It works, thank you <3
