### ISSUE TITLE
Cannot add YouTube subscription

### ISSUE THREAD

**Issue by kdwk** [Tubefeeder/Pipeline#159]
1. Try to add a YouTube subscription by typing in channel name
2. [2023-08-05T10:26:55Z ERROR tf_platform_youtube::subscription] Got back a error: expected value at line 1 column 1
[2023-08-05T10:26:55Z ERROR tubefeeder::gui::subscription::subscription_page::imp] Failed to get subscription with supplied data

**Comment by Schmiddiii** [comment]
Could you try to change the Piped API url to an alternative on from [here](https://github.com/TeamPiped/Piped/wiki/Instances) and try again?

**Comment by kdwk** [comment]
That worked.
